"""empty message

Revision ID: 02283e5b5ed7
Revises: 8afde855c749
Create Date: 2022-08-18 11:12:00.705566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02283e5b5ed7'
down_revision = '8afde855c749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_reset_captcha', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_reset_captcha', sa.Column('password', mysql.VARCHAR(length=200), nullable=False))
    # ### end Alembic commands ###
