"""empty message

Revision ID: 06760b562163
Revises: d43b13e0e521
Create Date: 2022-08-17 16:24:45.531155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06760b562163'
down_revision = 'd43b13e0e521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_reset_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('captcha', sa.String(length=10), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_reset_captcha')
    # ### end Alembic commands ###
