"""empty message

Revision ID: 8afde855c749
Revises: 06760b562163
Create Date: 2022-08-18 10:41:32.411163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8afde855c749'
down_revision = '06760b562163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_reset_captcha', sa.Column('password', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_reset_captcha', 'password')
    # ### end Alembic commands ###
